---

# project name, derived from parent folder, e.g. fvang
project_name: "{{ playbook_dir | dirname | basename }}"

# host name where site will be served, e.g. fvang.local
host_name: "{{ project_name }}.local"

# linux user who will own project files
user_name: "{{ ansible_user }}"

# home path for project and virtualenv, e.g. /home/ubuntu
home_path: /home/{{ user_name }}

# project path, e.g. /home/ubuntu/project
project_path: "{{ home_path }}/{{ project_name }}"

# flask app path, e.g. /home/ubuntu/project/src
application_path: "{{ project_path }}/src"

# public path, e.g. /home/ubuntu/project/public
public_path: "{{ project_path }}/public"

