---

- name: Playbook for production
  hosts: all
  become: yes

  vars:
    # project name, e.g. fvang
    project_name: "{{ playbook_dir | dirname | basename }}"

    # host name where site will be served, e.g. fvang.io
    host_name: "{{ project_name }}.io"

    # linux user who will own project files in home folder
    user_name: "{{ ansible_user }}"

    # production gunicorn
    gunicorn_enabled: true

    # production nginx
    nginx_use_ssl: false
    nginx_enabled: true

  roles:
    - project
